create table additive (id int8 not null, primary key (id));
create table batch (id  bigserial not null, rager_ibu numeric(19, 2), tinseth_ibu numeric(19, 2), alcohol_volume numeric(19, 2), amount_of_priming_material int4 not null, batch_number int4, blg1 numeric(19, 2), blg2 numeric(19, 2), boiling_time int4, bottling_date date, calculated_ibu numeric(19, 2), creation_date date, designation varchar(255), efficiency numeric(19, 2), fermentation_date date, lautering_type varchar(255), lautering_water_amount int4 check (lautering_water_amount<=20), mashing_water_amount int4 check (mashing_water_amount<=20), maturation_date date, priming_material varchar(255), volume numeric(4, 1), batch_comments_id int8, beer_style_id int8, primary key (id));
create table batch_comments (id  bigserial not null, comment text, batch_id int8, primary key (id));
create table batch_ingredient (amount int4 not null, batch_id int8 not null, ingredient_id int8 not null, way_of_serving varchar(255) not null, primary key (amount, batch_id, ingredient_id, way_of_serving));
create table batch_mash_temperature (batch_id int8 not null, mash_temperature_id int8 not null, minutes int4 not null, sequence int4 not null, primary key (batch_id, mash_temperature_id, minutes, sequence));
create table beer_style (id  bigserial not null, abv1 numeric(4, 1), abv2 numeric(4, 1), beer_style_name varchar(255), ebc1 int4 check (ebc1>=1), ebc2 int4 check (ebc2>=1), final_blg_1 numeric(4, 1), final_blg_2 numeric(4, 1), final_gravity_1 numeric(4, 3), final_gravity_2 numeric(4, 3), ibu1 int4 check (ibu1>=1), ibu2 int4 check (ibu2>=1), original_blg_1 numeric(4, 1), original_blg_2 numeric(4, 1), original_gravity_1 numeric(4, 3), original_gravity_2 numeric(4, 3), srm1 int4, srm2 int4, primary key (id));
create table country (id  bigserial not null, country_code varchar(255), country_name varchar(255), primary key (id));
create table hop (alpha_acid_max numeric(3, 1), alpha_acid_min numeric(3, 1), aroma_hop boolean, bitter_hop boolean, id int8 not null, country_id int8, primary key (id));
create table ingredient (type varchar(31) not null, id  bigserial not null, name varchar(255), primary key (id));
create table malt (malt_ebc int4, malt_filling int4, malt_usage varchar(255), id int8 not null, country_id int8, producer_id int8 not null, primary key (id));
create table mash_temperature (id  bigserial not null, description varchar(255), rest_name varchar(255), temp1 int4, temp2 int4, primary key (id));
create table producer (id  bigserial not null, producer_name varchar(255), product varchar(255), primary key (id));
create table yeast (alcohol_tolerance numeric(2, 0), fermentation_temp_max numeric(3, 1), fermentation_temp_min numeric(3, 1), flocculation int4, fermentation_type int4, yeast_type varchar(255), id int8 not null, producer_id int8, primary key (id));
alter table beer_style add constraint UK_sowx1f440q3tqgxq5wc67l59e unique (beer_style_name);
alter table country add constraint UK_qrkn270121aljmucrdbnmd35p unique (country_name);
alter table additive add constraint FKs71wv6q8broma753ungc4s8i foreign key (id) references ingredient;
alter table batch add constraint FKseg5h3yqh1uyfl46vut0o8fay foreign key (batch_comments_id) references batch_comments;
alter table batch add constraint FKkhjvygi25r299vx1dx7pjqvcy foreign key (beer_style_id) references beer_style;
alter table batch_comments add constraint FKs4tce7mavhst58nkvmwb7euek foreign key (batch_id) references batch;
alter table batch_ingredient add constraint FKlfko1nq7bp1tue31uijr8kdkw foreign key (batch_id) references batch;
alter table batch_ingredient add constraint FKfwsoy5y5sgvxecegg9a7n4xmj foreign key (ingredient_id) references ingredient;
alter table batch_mash_temperature add constraint FK7w59yuwy97q2d960hnbmc49ny foreign key (batch_id) references batch;
alter table batch_mash_temperature add constraint FKbojm3lss3qhq6wftqfc0k5cka foreign key (mash_temperature_id) references mash_temperature;
alter table hop add constraint FKq9k4gqqviv7qiiu2kfe0x7cc foreign key (country_id) references country;
alter table hop add constraint FKnw8lbijgra4k1vvmutqcdqhbs foreign key (id) references ingredient;
alter table malt add constraint FKoic4jn99yvdjep9wlxy0fc6jg foreign key (country_id) references country;
alter table malt add constraint FKp4nne04jqsxhkmrmamvaof9ca foreign key (producer_id) references producer;
alter table malt add constraint FKp07pikubnyw581g9axvp3dld4 foreign key (id) references ingredient;
alter table yeast add constraint FK64ef7w304mr2wmahw1jypqfnh foreign key (producer_id) references producer;
alter table yeast add constraint FK2tixgnwt8iaj2j8bk6epkgb9f foreign key (id) references ingredient;
create table additive (id int8 not null, primary key (id));
create table batch (id  bigserial not null, rager_ibu numeric(19, 2), tinseth_ibu numeric(19, 2), alcohol_volume numeric(19, 2), amount_of_priming_material int4 not null, batch_number int4, blg1 numeric(19, 2), blg2 numeric(19, 2), boiling_time int4, bottling_date date, calculated_ibu numeric(19, 2), creation_date date, designation varchar(255), efficiency numeric(19, 2), fermentation_date date, lautering_type varchar(255), lautering_water_amount int4 check (lautering_water_amount<=20), mashing_water_amount int4 check (mashing_water_amount<=20), maturation_date date, priming_material varchar(255), volume numeric(4, 1), batch_comments_id int8, beer_style_id int8, primary key (id));
create table batch_comments (id  bigserial not null, comment text, batch_id int8, primary key (id));
create table batch_ingredient (amount int4 not null, batch_id int8 not null, ingredient_id int8 not null, way_of_serving varchar(255) not null, primary key (amount, batch_id, ingredient_id, way_of_serving));
create table batch_mash_temperature (batch_id int8 not null, mash_temperature_id int8 not null, minutes int4 not null, sequence int4 not null, primary key (batch_id, mash_temperature_id, minutes, sequence));
create table beer_style (id  bigserial not null, abv1 numeric(4, 1), abv2 numeric(4, 1), beer_style_name varchar(255), ebc1 int4 check (ebc1>=1), ebc2 int4 check (ebc2>=1), final_blg_1 numeric(4, 1), final_blg_2 numeric(4, 1), final_gravity_1 numeric(4, 3), final_gravity_2 numeric(4, 3), ibu1 int4 check (ibu1>=1), ibu2 int4 check (ibu2>=1), original_blg_1 numeric(4, 1), original_blg_2 numeric(4, 1), original_gravity_1 numeric(4, 3), original_gravity_2 numeric(4, 3), srm1 int4, srm2 int4, primary key (id));
create table country (id  bigserial not null, country_code varchar(255), country_name varchar(255), primary key (id));
create table hop (alpha_acid_max numeric(3, 1), alpha_acid_min numeric(3, 1), aroma_hop boolean, bitter_hop boolean, id int8 not null, country_id int8, primary key (id));
create table ingredient (type varchar(31) not null, id  bigserial not null, name varchar(255), primary key (id));
create table malt (malt_ebc int4, malt_filling int4, malt_usage varchar(255), id int8 not null, country_id int8, producer_id int8 not null, primary key (id));
create table mash_temperature (id  bigserial not null, description varchar(255), rest_name varchar(255), temp1 int4, temp2 int4, primary key (id));
create table producer (id  bigserial not null, producer_name varchar(255), product varchar(255), primary key (id));
create table yeast (alcohol_tolerance numeric(2, 0), fermentation_temp_max numeric(3, 1), fermentation_temp_min numeric(3, 1), flocculation int4, fermentation_type int4, yeast_type varchar(255), id int8 not null, producer_id int8, primary key (id));
alter table beer_style add constraint UK_sowx1f440q3tqgxq5wc67l59e unique (beer_style_name);
alter table country add constraint UK_qrkn270121aljmucrdbnmd35p unique (country_name);
alter table additive add constraint FKs71wv6q8broma753ungc4s8i foreign key (id) references ingredient;
alter table batch add constraint FKseg5h3yqh1uyfl46vut0o8fay foreign key (batch_comments_id) references batch_comments;
alter table batch add constraint FKkhjvygi25r299vx1dx7pjqvcy foreign key (beer_style_id) references beer_style;
alter table batch_comments add constraint FKs4tce7mavhst58nkvmwb7euek foreign key (batch_id) references batch;
alter table batch_ingredient add constraint FKlfko1nq7bp1tue31uijr8kdkw foreign key (batch_id) references batch;
alter table batch_ingredient add constraint FKfwsoy5y5sgvxecegg9a7n4xmj foreign key (ingredient_id) references ingredient;
alter table batch_mash_temperature add constraint FK7w59yuwy97q2d960hnbmc49ny foreign key (batch_id) references batch;
alter table batch_mash_temperature add constraint FKbojm3lss3qhq6wftqfc0k5cka foreign key (mash_temperature_id) references mash_temperature;
alter table hop add constraint FKq9k4gqqviv7qiiu2kfe0x7cc foreign key (country_id) references country;
alter table hop add constraint FKnw8lbijgra4k1vvmutqcdqhbs foreign key (id) references ingredient;
alter table malt add constraint FKoic4jn99yvdjep9wlxy0fc6jg foreign key (country_id) references country;
alter table malt add constraint FKp4nne04jqsxhkmrmamvaof9ca foreign key (producer_id) references producer;
alter table malt add constraint FKp07pikubnyw581g9axvp3dld4 foreign key (id) references ingredient;
alter table yeast add constraint FK64ef7w304mr2wmahw1jypqfnh foreign key (producer_id) references producer;
alter table yeast add constraint FK2tixgnwt8iaj2j8bk6epkgb9f foreign key (id) references ingredient;
create table additive (id int8 not null, primary key (id));
create table batch (id  bigserial not null, rager_ibu numeric(19, 2), tinseth_ibu numeric(19, 2), alcohol_volume numeric(19, 2), amount_of_priming_material int4 not null, batch_number int4, blg1 numeric(19, 2), blg2 numeric(19, 2), boiling_time int4, bottling_date date, calculated_ibu numeric(19, 2), creation_date date, designation varchar(255), efficiency numeric(19, 2), fermentation_date date, lautering_type varchar(255), lautering_water_amount int4 check (lautering_water_amount<=20), mashing_water_amount int4 check (mashing_water_amount<=20), maturation_date date, priming_material varchar(255), volume numeric(4, 1), batch_comments_id int8, beer_style_id int8, primary key (id));
create table batch_comments (id  bigserial not null, comment text, batch_id int8, primary key (id));
create table batch_ingredient (amount int4 not null, batch_id int8 not null, ingredient_id int8 not null, way_of_serving varchar(255) not null, primary key (amount, batch_id, ingredient_id, way_of_serving));
create table batch_mash_temperature (batch_id int8 not null, mash_temperature_id int8 not null, minutes int4 not null, sequence int4 not null, primary key (batch_id, mash_temperature_id, minutes, sequence));
create table beer_style (id  bigserial not null, abv1 numeric(4, 1), abv2 numeric(4, 1), beer_style_name varchar(255), ebc1 int4 check (ebc1>=1), ebc2 int4 check (ebc2>=1), final_blg_1 numeric(4, 1), final_blg_2 numeric(4, 1), final_gravity_1 numeric(4, 3), final_gravity_2 numeric(4, 3), ibu1 int4 check (ibu1>=1), ibu2 int4 check (ibu2>=1), original_blg_1 numeric(4, 1), original_blg_2 numeric(4, 1), original_gravity_1 numeric(4, 3), original_gravity_2 numeric(4, 3), srm1 int4, srm2 int4, primary key (id));
create table country (id  bigserial not null, country_code varchar(255), country_name varchar(255), primary key (id));
create table hop (alpha_acid_max numeric(3, 1), alpha_acid_min numeric(3, 1), aroma_hop boolean, bitter_hop boolean, id int8 not null, country_id int8, primary key (id));
create table ingredient (type varchar(31) not null, id  bigserial not null, name varchar(255), primary key (id));
create table malt (malt_ebc int4, malt_filling int4, malt_usage varchar(255), id int8 not null, country_id int8, producer_id int8 not null, primary key (id));
create table mash_temperature (id  bigserial not null, description varchar(255), rest_name varchar(255), temp1 int4, temp2 int4, primary key (id));
create table producer (id  bigserial not null, producer_name varchar(255), product varchar(255), primary key (id));
create table yeast (alcohol_tolerance numeric(2, 0), fermentation_temp_max numeric(3, 1), fermentation_temp_min numeric(3, 1), flocculation int4, fermentation_type int4, yeast_type varchar(255), id int8 not null, producer_id int8, primary key (id));
alter table beer_style add constraint UK_sowx1f440q3tqgxq5wc67l59e unique (beer_style_name);
alter table country add constraint UK_qrkn270121aljmucrdbnmd35p unique (country_name);
alter table additive add constraint FKs71wv6q8broma753ungc4s8i foreign key (id) references ingredient;
alter table batch add constraint FKseg5h3yqh1uyfl46vut0o8fay foreign key (batch_comments_id) references batch_comments;
alter table batch add constraint FKkhjvygi25r299vx1dx7pjqvcy foreign key (beer_style_id) references beer_style;
alter table batch_comments add constraint FKs4tce7mavhst58nkvmwb7euek foreign key (batch_id) references batch;
alter table batch_ingredient add constraint FKlfko1nq7bp1tue31uijr8kdkw foreign key (batch_id) references batch;
alter table batch_ingredient add constraint FKfwsoy5y5sgvxecegg9a7n4xmj foreign key (ingredient_id) references ingredient;
alter table batch_mash_temperature add constraint FK7w59yuwy97q2d960hnbmc49ny foreign key (batch_id) references batch;
alter table batch_mash_temperature add constraint FKbojm3lss3qhq6wftqfc0k5cka foreign key (mash_temperature_id) references mash_temperature;
alter table hop add constraint FKq9k4gqqviv7qiiu2kfe0x7cc foreign key (country_id) references country;
alter table hop add constraint FKnw8lbijgra4k1vvmutqcdqhbs foreign key (id) references ingredient;
alter table malt add constraint FKoic4jn99yvdjep9wlxy0fc6jg foreign key (country_id) references country;
alter table malt add constraint FKp4nne04jqsxhkmrmamvaof9ca foreign key (producer_id) references producer;
alter table malt add constraint FKp07pikubnyw581g9axvp3dld4 foreign key (id) references ingredient;
alter table yeast add constraint FK64ef7w304mr2wmahw1jypqfnh foreign key (producer_id) references producer;
alter table yeast add constraint FK2tixgnwt8iaj2j8bk6epkgb9f foreign key (id) references ingredient;
create table additive (id int8 not null, primary key (id));
create table batch (id  bigserial not null, rager_ibu numeric(19, 2), tinseth_ibu numeric(19, 2), alcohol_volume numeric(19, 2), amount_of_priming_material int4 not null, batch_number int4, blg1 numeric(19, 2), blg2 numeric(19, 2), boiling_time int4, bottling_date date, calculated_ibu numeric(19, 2), creation_date date, designation varchar(255), efficiency numeric(19, 2), fermentation_date date, lautering_type varchar(255), lautering_water_amount int4 check (lautering_water_amount<=20), mashing_water_amount int4 check (mashing_water_amount<=20), maturation_date date, priming_material varchar(255), volume numeric(4, 1), batch_comments_id int8, beer_style_id int8, primary key (id));
create table batch_comments (id  bigserial not null, comment text, batch_id int8, primary key (id));
create table batch_ingredient (amount int4 not null, batch_id int8 not null, ingredient_id int8 not null, way_of_serving varchar(255) not null, primary key (amount, batch_id, ingredient_id, way_of_serving));
create table batch_mash_temperature (batch_id int8 not null, mash_temperature_id int8 not null, minutes int4 not null, sequence int4 not null, primary key (batch_id, mash_temperature_id, minutes, sequence));
create table beer_style (id  bigserial not null, abv1 numeric(4, 1), abv2 numeric(4, 1), beer_style_name varchar(255), ebc1 int4 check (ebc1>=1), ebc2 int4 check (ebc2>=1), final_blg_1 numeric(4, 1), final_blg_2 numeric(4, 1), final_gravity_1 numeric(4, 3), final_gravity_2 numeric(4, 3), ibu1 int4 check (ibu1>=1), ibu2 int4 check (ibu2>=1), original_blg_1 numeric(4, 1), original_blg_2 numeric(4, 1), original_gravity_1 numeric(4, 3), original_gravity_2 numeric(4, 3), srm1 int4, srm2 int4, primary key (id));
create table country (id  bigserial not null, country_code varchar(255), country_name varchar(255), primary key (id));
create table hop (alpha_acid_max numeric(3, 1), alpha_acid_min numeric(3, 1), aroma_hop boolean, bitter_hop boolean, id int8 not null, country_id int8, primary key (id));
create table ingredient (type varchar(31) not null, id  bigserial not null, name varchar(255), primary key (id));
create table malt (malt_ebc int4, malt_filling int4, malt_usage varchar(255), id int8 not null, country_id int8, producer_id int8 not null, primary key (id));
create table mash_temperature (id  bigserial not null, description varchar(255), rest_name varchar(255), temp1 int4, temp2 int4, primary key (id));
create table producer (id  bigserial not null, producer_name varchar(255), product varchar(255), primary key (id));
create table yeast (alcohol_tolerance numeric(2, 0), fermentation_temp_max numeric(3, 1), fermentation_temp_min numeric(3, 1), flocculation int4, fermentation_type int4, yeast_type varchar(255), id int8 not null, producer_id int8, primary key (id));
alter table beer_style add constraint UK_sowx1f440q3tqgxq5wc67l59e unique (beer_style_name);
alter table country add constraint UK_qrkn270121aljmucrdbnmd35p unique (country_name);
alter table additive add constraint FKs71wv6q8broma753ungc4s8i foreign key (id) references ingredient;
alter table batch add constraint FKseg5h3yqh1uyfl46vut0o8fay foreign key (batch_comments_id) references batch_comments;
alter table batch add constraint FKkhjvygi25r299vx1dx7pjqvcy foreign key (beer_style_id) references beer_style;
alter table batch_comments add constraint FKs4tce7mavhst58nkvmwb7euek foreign key (batch_id) references batch;
alter table batch_ingredient add constraint FKlfko1nq7bp1tue31uijr8kdkw foreign key (batch_id) references batch;
alter table batch_ingredient add constraint FKfwsoy5y5sgvxecegg9a7n4xmj foreign key (ingredient_id) references ingredient;
alter table batch_mash_temperature add constraint FK7w59yuwy97q2d960hnbmc49ny foreign key (batch_id) references batch;
alter table batch_mash_temperature add constraint FKbojm3lss3qhq6wftqfc0k5cka foreign key (mash_temperature_id) references mash_temperature;
alter table hop add constraint FKq9k4gqqviv7qiiu2kfe0x7cc foreign key (country_id) references country;
alter table hop add constraint FKnw8lbijgra4k1vvmutqcdqhbs foreign key (id) references ingredient;
alter table malt add constraint FKoic4jn99yvdjep9wlxy0fc6jg foreign key (country_id) references country;
alter table malt add constraint FKp4nne04jqsxhkmrmamvaof9ca foreign key (producer_id) references producer;
alter table malt add constraint FKp07pikubnyw581g9axvp3dld4 foreign key (id) references ingredient;
alter table yeast add constraint FK64ef7w304mr2wmahw1jypqfnh foreign key (producer_id) references producer;
alter table yeast add constraint FK2tixgnwt8iaj2j8bk6epkgb9f foreign key (id) references ingredient;
create table additive (id int8 not null, primary key (id));
create table batch (id  bigserial not null, rager_ibu numeric(19, 2), tinseth_ibu numeric(19, 2), alcohol_volume numeric(19, 2), amount_of_priming_material int4 not null, batch_number int4, blg1 numeric(19, 2), blg2 numeric(19, 2), boiling_time int4, bottling_date date, calculated_ibu numeric(19, 2), creation_date date, designation varchar(255), efficiency numeric(19, 2), fermentation_date date, lautering_type varchar(255), lautering_water_amount int4 check (lautering_water_amount<=20), mashing_water_amount int4 check (mashing_water_amount<=20), maturation_date date, priming_material varchar(255), volume numeric(4, 1), batch_comments_id int8, beer_style_id int8, primary key (id));
create table batch_comments (id  bigserial not null, comment text, batch_id int8, primary key (id));
create table batch_ingredient (amount int4 not null, batch_id int8 not null, ingredient_id int8 not null, way_of_serving varchar(255) not null, primary key (amount, batch_id, ingredient_id, way_of_serving));
create table batch_mash_temperature (batch_id int8 not null, mash_temperature_id int8 not null, minutes int4 not null, sequence int4 not null, primary key (batch_id, mash_temperature_id, minutes, sequence));
create table beer_style (id  bigserial not null, abv1 numeric(4, 1), abv2 numeric(4, 1), beer_style_name varchar(255), ebc1 int4 check (ebc1>=1), ebc2 int4 check (ebc2>=1), final_blg_1 numeric(4, 1), final_blg_2 numeric(4, 1), final_gravity_1 numeric(4, 3), final_gravity_2 numeric(4, 3), ibu1 int4 check (ibu1>=1), ibu2 int4 check (ibu2>=1), original_blg_1 numeric(4, 1), original_blg_2 numeric(4, 1), original_gravity_1 numeric(4, 3), original_gravity_2 numeric(4, 3), srm1 int4, srm2 int4, primary key (id));
create table country (id  bigserial not null, country_code varchar(255), country_name varchar(255), primary key (id));
create table hop (alpha_acid_max numeric(3, 1), alpha_acid_min numeric(3, 1), aroma_hop boolean, bitter_hop boolean, id int8 not null, country_id int8, primary key (id));
create table ingredient (type varchar(31) not null, id  bigserial not null, name varchar(255), primary key (id));
create table malt (malt_ebc int4, malt_filling int4, malt_usage varchar(255), id int8 not null, country_id int8, producer_id int8 not null, primary key (id));
create table mash_temperature (id  bigserial not null, description varchar(255), rest_name varchar(255), temp1 int4, temp2 int4, primary key (id));
create table producer (id  bigserial not null, producer_name varchar(255), product varchar(255), primary key (id));
create table yeast (alcohol_tolerance numeric(2, 0), fermentation_temp_max numeric(3, 1), fermentation_temp_min numeric(3, 1), flocculation int4, fermentation_type int4, yeast_type varchar(255), id int8 not null, producer_id int8, primary key (id));
alter table beer_style add constraint UK_sowx1f440q3tqgxq5wc67l59e unique (beer_style_name);
alter table country add constraint UK_qrkn270121aljmucrdbnmd35p unique (country_name);
alter table additive add constraint FKs71wv6q8broma753ungc4s8i foreign key (id) references ingredient;
alter table batch add constraint FKseg5h3yqh1uyfl46vut0o8fay foreign key (batch_comments_id) references batch_comments;
alter table batch add constraint FKkhjvygi25r299vx1dx7pjqvcy foreign key (beer_style_id) references beer_style;
alter table batch_comments add constraint FKs4tce7mavhst58nkvmwb7euek foreign key (batch_id) references batch;
alter table batch_ingredient add constraint FKlfko1nq7bp1tue31uijr8kdkw foreign key (batch_id) references batch;
alter table batch_ingredient add constraint FKfwsoy5y5sgvxecegg9a7n4xmj foreign key (ingredient_id) references ingredient;
alter table batch_mash_temperature add constraint FK7w59yuwy97q2d960hnbmc49ny foreign key (batch_id) references batch;
alter table batch_mash_temperature add constraint FKbojm3lss3qhq6wftqfc0k5cka foreign key (mash_temperature_id) references mash_temperature;
alter table hop add constraint FKq9k4gqqviv7qiiu2kfe0x7cc foreign key (country_id) references country;
alter table hop add constraint FKnw8lbijgra4k1vvmutqcdqhbs foreign key (id) references ingredient;
alter table malt add constraint FKoic4jn99yvdjep9wlxy0fc6jg foreign key (country_id) references country;
alter table malt add constraint FKp4nne04jqsxhkmrmamvaof9ca foreign key (producer_id) references producer;
alter table malt add constraint FKp07pikubnyw581g9axvp3dld4 foreign key (id) references ingredient;
alter table yeast add constraint FK64ef7w304mr2wmahw1jypqfnh foreign key (producer_id) references producer;
alter table yeast add constraint FK2tixgnwt8iaj2j8bk6epkgb9f foreign key (id) references ingredient;
create table additive (id int8 not null, primary key (id));
create table batch (id  bigserial not null, rager_ibu numeric(19, 2), tinseth_ibu numeric(19, 2), alcohol_volume numeric(19, 2), amount_of_priming_material int4 not null, batch_number int4, blg1 numeric(19, 2), blg2 numeric(19, 2), boiling_time int4, bottling_date date, calculated_ibu numeric(19, 2), creation_date date, designation varchar(255), efficiency numeric(19, 2), fermentation_date date, lautering_type varchar(255), lautering_water_amount int4 check (lautering_water_amount<=20), mashing_water_amount int4 check (mashing_water_amount<=20), maturation_date date, priming_material varchar(255), volume numeric(4, 1), batch_comments_id int8, beer_style_id int8, primary key (id));
create table batch_comments (id  bigserial not null, comment text, batch_id int8, primary key (id));
create table batch_ingredient (amount int4 not null, batch_id int8 not null, ingredient_id int8 not null, way_of_serving varchar(255) not null, primary key (amount, batch_id, ingredient_id, way_of_serving));
create table batch_mash_temperature (batch_id int8 not null, mash_temperature_id int8 not null, minutes int4 not null, sequence int4 not null, primary key (batch_id, mash_temperature_id, minutes, sequence));
create table beer_style (id  bigserial not null, abv1 numeric(4, 1), abv2 numeric(4, 1), beer_style_name varchar(255), ebc1 int4 check (ebc1>=1), ebc2 int4 check (ebc2>=1), final_blg_1 numeric(4, 1), final_blg_2 numeric(4, 1), final_gravity_1 numeric(4, 3), final_gravity_2 numeric(4, 3), ibu1 int4 check (ibu1>=1), ibu2 int4 check (ibu2>=1), original_blg_1 numeric(4, 1), original_blg_2 numeric(4, 1), original_gravity_1 numeric(4, 3), original_gravity_2 numeric(4, 3), srm1 int4, srm2 int4, primary key (id));
create table country (id  bigserial not null, country_code varchar(255), country_name varchar(255), primary key (id));
create table hop (alpha_acid_max numeric(3, 1), alpha_acid_min numeric(3, 1), aroma_hop boolean, bitter_hop boolean, id int8 not null, country_id int8, primary key (id));
create table ingredient (type varchar(31) not null, id  bigserial not null, name varchar(255), primary key (id));
create table malt (malt_ebc int4, malt_filling int4, malt_usage varchar(255), id int8 not null, country_id int8, producer_id int8 not null, primary key (id));
create table mash_temperature (id  bigserial not null, description varchar(255), rest_name varchar(255), temp1 int4, temp2 int4, primary key (id));
create table producer (id  bigserial not null, producer_name varchar(255), product varchar(255), primary key (id));
create table yeast (alcohol_tolerance numeric(2, 0), fermentation_temp_max numeric(3, 1), fermentation_temp_min numeric(3, 1), flocculation int4, fermentation_type int4, yeast_type varchar(255), id int8 not null, producer_id int8, primary key (id));
alter table beer_style add constraint UK_sowx1f440q3tqgxq5wc67l59e unique (beer_style_name);
alter table country add constraint UK_qrkn270121aljmucrdbnmd35p unique (country_name);
alter table additive add constraint FKs71wv6q8broma753ungc4s8i foreign key (id) references ingredient;
alter table batch add constraint FKseg5h3yqh1uyfl46vut0o8fay foreign key (batch_comments_id) references batch_comments;
alter table batch add constraint FKkhjvygi25r299vx1dx7pjqvcy foreign key (beer_style_id) references beer_style;
alter table batch_comments add constraint FKs4tce7mavhst58nkvmwb7euek foreign key (batch_id) references batch;
alter table batch_ingredient add constraint FKlfko1nq7bp1tue31uijr8kdkw foreign key (batch_id) references batch;
alter table batch_ingredient add constraint FKfwsoy5y5sgvxecegg9a7n4xmj foreign key (ingredient_id) references ingredient;
alter table batch_mash_temperature add constraint FK7w59yuwy97q2d960hnbmc49ny foreign key (batch_id) references batch;
alter table batch_mash_temperature add constraint FKbojm3lss3qhq6wftqfc0k5cka foreign key (mash_temperature_id) references mash_temperature;
alter table hop add constraint FKq9k4gqqviv7qiiu2kfe0x7cc foreign key (country_id) references country;
alter table hop add constraint FKnw8lbijgra4k1vvmutqcdqhbs foreign key (id) references ingredient;
alter table malt add constraint FKoic4jn99yvdjep9wlxy0fc6jg foreign key (country_id) references country;
alter table malt add constraint FKp4nne04jqsxhkmrmamvaof9ca foreign key (producer_id) references producer;
alter table malt add constraint FKp07pikubnyw581g9axvp3dld4 foreign key (id) references ingredient;
alter table yeast add constraint FK64ef7w304mr2wmahw1jypqfnh foreign key (producer_id) references producer;
alter table yeast add constraint FK2tixgnwt8iaj2j8bk6epkgb9f foreign key (id) references ingredient;
create table additive (id int8 not null, primary key (id));
create table batch (id  bigserial not null, rager_ibu numeric(19, 2), tinseth_ibu numeric(19, 2), alcohol_volume numeric(19, 2), amount_of_priming_material int4 not null, batch_number int4, blg1 numeric(19, 2), blg2 numeric(19, 2), boiling_time int4, bottling_date date, calculated_ibu numeric(19, 2), creation_date date, designation varchar(255), efficiency numeric(19, 2), fermentation_date date, lautering_type varchar(255), lautering_water_amount int4 check (lautering_water_amount<=20), mashing_water_amount int4 check (mashing_water_amount<=20), maturation_date date, priming_material varchar(255), volume numeric(4, 1), batch_comments_id int8, beer_style_id int8, primary key (id));
create table batch_comments (id  bigserial not null, comment text, batch_id int8, primary key (id));
create table batch_ingredient (amount int4 not null, batch_id int8 not null, ingredient_id int8 not null, way_of_serving varchar(255) not null, primary key (amount, batch_id, ingredient_id, way_of_serving));
create table batch_mash_temperature (batch_id int8 not null, mash_temperature_id int8 not null, minutes int4 not null, sequence int4 not null, primary key (batch_id, mash_temperature_id, minutes, sequence));
create table beer_style (id  bigserial not null, abv1 numeric(4, 1), abv2 numeric(4, 1), beer_style_name varchar(255), ebc1 int4 check (ebc1>=1), ebc2 int4 check (ebc2>=1), final_blg_1 numeric(4, 1), final_blg_2 numeric(4, 1), final_gravity_1 numeric(4, 3), final_gravity_2 numeric(4, 3), ibu1 int4 check (ibu1>=1), ibu2 int4 check (ibu2>=1), original_blg_1 numeric(4, 1), original_blg_2 numeric(4, 1), original_gravity_1 numeric(4, 3), original_gravity_2 numeric(4, 3), srm1 int4, srm2 int4, primary key (id));
create table country (id  bigserial not null, country_code varchar(255), country_name varchar(255), primary key (id));
create table hop (alpha_acid_max numeric(3, 1), alpha_acid_min numeric(3, 1), aroma_hop boolean, bitter_hop boolean, id int8 not null, country_id int8, primary key (id));
create table ingredient (type varchar(31) not null, id  bigserial not null, name varchar(255), primary key (id));
create table malt (malt_ebc int4, malt_filling int4, malt_usage varchar(255), id int8 not null, country_id int8, producer_id int8 not null, primary key (id));
create table mash_temperature (id  bigserial not null, description varchar(255), rest_name varchar(255), temp1 int4, temp2 int4, primary key (id));
create table producer (id  bigserial not null, producer_name varchar(255), product varchar(255), primary key (id));
create table yeast (alcohol_tolerance numeric(2, 0), fermentation_temp_max numeric(3, 1), fermentation_temp_min numeric(3, 1), flocculation int4, fermentation_type int4, yeast_type varchar(255), id int8 not null, producer_id int8, primary key (id));
alter table beer_style add constraint UK_sowx1f440q3tqgxq5wc67l59e unique (beer_style_name);
alter table country add constraint UK_qrkn270121aljmucrdbnmd35p unique (country_name);
alter table additive add constraint FKs71wv6q8broma753ungc4s8i foreign key (id) references ingredient;
alter table batch add constraint FKseg5h3yqh1uyfl46vut0o8fay foreign key (batch_comments_id) references batch_comments;
alter table batch add constraint FKkhjvygi25r299vx1dx7pjqvcy foreign key (beer_style_id) references beer_style;
alter table batch_comments add constraint FKs4tce7mavhst58nkvmwb7euek foreign key (batch_id) references batch;
alter table batch_ingredient add constraint FKlfko1nq7bp1tue31uijr8kdkw foreign key (batch_id) references batch;
alter table batch_ingredient add constraint FKfwsoy5y5sgvxecegg9a7n4xmj foreign key (ingredient_id) references ingredient;
alter table batch_mash_temperature add constraint FK7w59yuwy97q2d960hnbmc49ny foreign key (batch_id) references batch;
alter table batch_mash_temperature add constraint FKbojm3lss3qhq6wftqfc0k5cka foreign key (mash_temperature_id) references mash_temperature;
alter table hop add constraint FKq9k4gqqviv7qiiu2kfe0x7cc foreign key (country_id) references country;
alter table hop add constraint FKnw8lbijgra4k1vvmutqcdqhbs foreign key (id) references ingredient;
alter table malt add constraint FKoic4jn99yvdjep9wlxy0fc6jg foreign key (country_id) references country;
alter table malt add constraint FKp4nne04jqsxhkmrmamvaof9ca foreign key (producer_id) references producer;
alter table malt add constraint FKp07pikubnyw581g9axvp3dld4 foreign key (id) references ingredient;
alter table yeast add constraint FK64ef7w304mr2wmahw1jypqfnh foreign key (producer_id) references producer;
alter table yeast add constraint FK2tixgnwt8iaj2j8bk6epkgb9f foreign key (id) references ingredient;
create table additive (id int8 not null, primary key (id));
create table batch (id  bigserial not null, rager_ibu numeric(19, 2), tinseth_ibu numeric(19, 2), alcohol_volume numeric(19, 2), amount_of_priming_material int4 not null, batch_number int4, blg1 numeric(19, 2), blg2 numeric(19, 2), boiling_time int4, bottling_date date, calculated_ibu numeric(19, 2), creation_date date, designation varchar(255), efficiency numeric(19, 2), fermentation_date date, lautering_type varchar(255), lautering_water_amount int4 check (lautering_water_amount<=20), mashing_water_amount int4 check (mashing_water_amount<=20), maturation_date date, priming_material varchar(255), volume numeric(4, 1), batch_comments_id int8, beer_style_id int8, primary key (id));
create table batch_comments (id  bigserial not null, comment text, batch_id int8, primary key (id));
create table batch_ingredient (amount int4 not null, batch_id int8 not null, ingredient_id int8 not null, way_of_serving varchar(255) not null, primary key (amount, batch_id, ingredient_id, way_of_serving));
create table batch_mash_temperature (batch_id int8 not null, mash_temperature_id int8 not null, minutes int4 not null, sequence int4 not null, primary key (batch_id, mash_temperature_id, minutes, sequence));
create table beer_style (id  bigserial not null, abv1 numeric(4, 1), abv2 numeric(4, 1), beer_style_name varchar(255), ebc1 int4 check (ebc1>=1), ebc2 int4 check (ebc2>=1), final_blg_1 numeric(4, 1), final_blg_2 numeric(4, 1), final_gravity_1 numeric(4, 3), final_gravity_2 numeric(4, 3), ibu1 int4 check (ibu1>=1), ibu2 int4 check (ibu2>=1), original_blg_1 numeric(4, 1), original_blg_2 numeric(4, 1), original_gravity_1 numeric(4, 3), original_gravity_2 numeric(4, 3), srm1 int4, srm2 int4, primary key (id));
create table country (id  bigserial not null, country_code varchar(255), country_name varchar(255), primary key (id));
create table hop (alpha_acid_max numeric(3, 1), alpha_acid_min numeric(3, 1), aroma_hop boolean, bitter_hop boolean, id int8 not null, country_id int8, primary key (id));
create table ingredient (type varchar(31) not null, id  bigserial not null, name varchar(255), primary key (id));
create table malt (malt_ebc int4, malt_filling int4, malt_usage varchar(255), id int8 not null, country_id int8, producer_id int8 not null, primary key (id));
create table mash_temperature (id  bigserial not null, description varchar(255), rest_name varchar(255), temp1 int4, temp2 int4, primary key (id));
create table producer (id  bigserial not null, producer_name varchar(255), product varchar(255), primary key (id));
create table yeast (alcohol_tolerance numeric(2, 0), fermentation_temp_max numeric(3, 1), fermentation_temp_min numeric(3, 1), flocculation int4, fermentation_type int4, yeast_type varchar(255), id int8 not null, producer_id int8, primary key (id));
alter table beer_style add constraint UK_sowx1f440q3tqgxq5wc67l59e unique (beer_style_name);
alter table country add constraint UK_qrkn270121aljmucrdbnmd35p unique (country_name);
alter table additive add constraint FKs71wv6q8broma753ungc4s8i foreign key (id) references ingredient;
alter table batch add constraint FKseg5h3yqh1uyfl46vut0o8fay foreign key (batch_comments_id) references batch_comments;
alter table batch add constraint FKkhjvygi25r299vx1dx7pjqvcy foreign key (beer_style_id) references beer_style;
alter table batch_comments add constraint FKs4tce7mavhst58nkvmwb7euek foreign key (batch_id) references batch;
alter table batch_ingredient add constraint FKlfko1nq7bp1tue31uijr8kdkw foreign key (batch_id) references batch;
alter table batch_ingredient add constraint FKfwsoy5y5sgvxecegg9a7n4xmj foreign key (ingredient_id) references ingredient;
alter table batch_mash_temperature add constraint FK7w59yuwy97q2d960hnbmc49ny foreign key (batch_id) references batch;
alter table batch_mash_temperature add constraint FKbojm3lss3qhq6wftqfc0k5cka foreign key (mash_temperature_id) references mash_temperature;
alter table hop add constraint FKq9k4gqqviv7qiiu2kfe0x7cc foreign key (country_id) references country;
alter table hop add constraint FKnw8lbijgra4k1vvmutqcdqhbs foreign key (id) references ingredient;
alter table malt add constraint FKoic4jn99yvdjep9wlxy0fc6jg foreign key (country_id) references country;
alter table malt add constraint FKp4nne04jqsxhkmrmamvaof9ca foreign key (producer_id) references producer;
alter table malt add constraint FKp07pikubnyw581g9axvp3dld4 foreign key (id) references ingredient;
alter table yeast add constraint FK64ef7w304mr2wmahw1jypqfnh foreign key (producer_id) references producer;
alter table yeast add constraint FK2tixgnwt8iaj2j8bk6epkgb9f foreign key (id) references ingredient;
create table additive (id int8 not null, primary key (id));
create table batch (id  bigserial not null, rager_ibu numeric(19, 2), tinseth_ibu numeric(19, 2), alcohol_volume numeric(19, 2), amount_of_priming_material int4 not null, batch_number int4, blg1 numeric(19, 2), blg2 numeric(19, 2), boiling_time int4, bottling_date date, calculated_ibu numeric(19, 2), creation_date date, designation varchar(255), efficiency numeric(19, 2), fermentation_date date, lautering_type varchar(255), lautering_water_amount int4 check (lautering_water_amount<=20), mashing_water_amount int4 check (mashing_water_amount<=20), maturation_date date, priming_material varchar(255), volume numeric(4, 1), batch_comments_id int8, beer_style_id int8, primary key (id));
create table batch_comments (id  bigserial not null, comment text, batch_id int8, primary key (id));
create table batch_ingredient (amount int4 not null, batch_id int8 not null, ingredient_id int8 not null, way_of_serving varchar(255) not null, primary key (amount, batch_id, ingredient_id, way_of_serving));
create table batch_mash_temperature (batch_id int8 not null, mash_temperature_id int8 not null, minutes int4 not null, sequence int4 not null, primary key (batch_id, mash_temperature_id, minutes, sequence));
create table beer_style (id  bigserial not null, abv1 numeric(4, 1), abv2 numeric(4, 1), beer_style_name varchar(255), ebc1 int4 check (ebc1>=1), ebc2 int4 check (ebc2>=1), final_blg_1 numeric(4, 1), final_blg_2 numeric(4, 1), final_gravity_1 numeric(4, 3), final_gravity_2 numeric(4, 3), ibu1 int4 check (ibu1>=1), ibu2 int4 check (ibu2>=1), original_blg_1 numeric(4, 1), original_blg_2 numeric(4, 1), original_gravity_1 numeric(4, 3), original_gravity_2 numeric(4, 3), srm1 int4, srm2 int4, primary key (id));
create table country (id  bigserial not null, country_code varchar(255), country_name varchar(255), primary key (id));
create table hop (alpha_acid_max numeric(3, 1), alpha_acid_min numeric(3, 1), aroma_hop boolean, bitter_hop boolean, id int8 not null, country_id int8, primary key (id));
create table ingredient (type varchar(31) not null, id  bigserial not null, name varchar(255), primary key (id));
create table malt (malt_ebc int4, malt_filling int4, malt_usage varchar(255), id int8 not null, country_id int8, producer_id int8 not null, primary key (id));
create table mash_temperature (id  bigserial not null, description varchar(255), rest_name varchar(255), temp1 int4, temp2 int4, primary key (id));
create table producer (id  bigserial not null, producer_name varchar(255), product varchar(255), primary key (id));
create table yeast (alcohol_tolerance numeric(2, 0), fermentation_temp_max numeric(3, 1), fermentation_temp_min numeric(3, 1), flocculation int4, fermentation_type int4, yeast_type varchar(255), id int8 not null, producer_id int8, primary key (id));
alter table beer_style add constraint UK_sowx1f440q3tqgxq5wc67l59e unique (beer_style_name);
alter table country add constraint UK_qrkn270121aljmucrdbnmd35p unique (country_name);
alter table additive add constraint FKs71wv6q8broma753ungc4s8i foreign key (id) references ingredient;
alter table batch add constraint FKseg5h3yqh1uyfl46vut0o8fay foreign key (batch_comments_id) references batch_comments;
alter table batch add constraint FKkhjvygi25r299vx1dx7pjqvcy foreign key (beer_style_id) references beer_style;
alter table batch_comments add constraint FKs4tce7mavhst58nkvmwb7euek foreign key (batch_id) references batch;
alter table batch_ingredient add constraint FKlfko1nq7bp1tue31uijr8kdkw foreign key (batch_id) references batch;
alter table batch_ingredient add constraint FKfwsoy5y5sgvxecegg9a7n4xmj foreign key (ingredient_id) references ingredient;
alter table batch_mash_temperature add constraint FK7w59yuwy97q2d960hnbmc49ny foreign key (batch_id) references batch;
alter table batch_mash_temperature add constraint FKbojm3lss3qhq6wftqfc0k5cka foreign key (mash_temperature_id) references mash_temperature;
alter table hop add constraint FKq9k4gqqviv7qiiu2kfe0x7cc foreign key (country_id) references country;
alter table hop add constraint FKnw8lbijgra4k1vvmutqcdqhbs foreign key (id) references ingredient;
alter table malt add constraint FKoic4jn99yvdjep9wlxy0fc6jg foreign key (country_id) references country;
alter table malt add constraint FKp4nne04jqsxhkmrmamvaof9ca foreign key (producer_id) references producer;
alter table malt add constraint FKp07pikubnyw581g9axvp3dld4 foreign key (id) references ingredient;
alter table yeast add constraint FK64ef7w304mr2wmahw1jypqfnh foreign key (producer_id) references producer;
alter table yeast add constraint FK2tixgnwt8iaj2j8bk6epkgb9f foreign key (id) references ingredient;
create table additive (id int8 not null, primary key (id));
create table batch (id  bigserial not null, rager_ibu numeric(19, 2), tinseth_ibu numeric(19, 2), alcohol_volume numeric(19, 2), amount_of_priming_material int4 not null, batch_number int4, blg1 numeric(19, 2), blg2 numeric(19, 2), boiling_time int4, bottling_date date, calculated_ibu numeric(19, 2), creation_date date, designation varchar(255), efficiency numeric(19, 2), fermentation_date date, lautering_type varchar(255), lautering_water_amount int4 check (lautering_water_amount<=20), mashing_water_amount int4 check (mashing_water_amount<=20), maturation_date date, priming_material varchar(255), volume numeric(4, 1), batch_comments_id int8, beer_style_id int8, primary key (id));
create table batch_comments (id  bigserial not null, comment text, batch_id int8, primary key (id));
create table batch_ingredient (amount int4 not null, batch_id int8 not null, ingredient_id int8 not null, way_of_serving varchar(255) not null, primary key (amount, batch_id, ingredient_id, way_of_serving));
create table batch_mash_temperature (batch_id int8 not null, mash_temperature_id int8 not null, minutes int4 not null, sequence int4 not null, primary key (batch_id, mash_temperature_id, minutes, sequence));
create table beer_style (id  bigserial not null, abv1 numeric(4, 1), abv2 numeric(4, 1), beer_style_name varchar(255), ebc1 int4 check (ebc1>=1), ebc2 int4 check (ebc2>=1), final_blg_1 numeric(4, 1), final_blg_2 numeric(4, 1), final_gravity_1 numeric(4, 3), final_gravity_2 numeric(4, 3), ibu1 int4 check (ibu1>=1), ibu2 int4 check (ibu2>=1), original_blg_1 numeric(4, 1), original_blg_2 numeric(4, 1), original_gravity_1 numeric(4, 3), original_gravity_2 numeric(4, 3), srm1 int4, srm2 int4, primary key (id));
create table country (id  bigserial not null, country_code varchar(255), country_name varchar(255), primary key (id));
create table hop (alpha_acid_max numeric(3, 1), alpha_acid_min numeric(3, 1), aroma_hop boolean, bitter_hop boolean, id int8 not null, country_id int8, primary key (id));
create table ingredient (type varchar(31) not null, id  bigserial not null, name varchar(255), primary key (id));
create table malt (malt_ebc int4, malt_filling int4, malt_usage varchar(255), id int8 not null, country_id int8, producer_id int8 not null, primary key (id));
create table mash_temperature (id  bigserial not null, description varchar(255), rest_name varchar(255), temp1 int4, temp2 int4, primary key (id));
create table producer (id  bigserial not null, producer_name varchar(255), product varchar(255), primary key (id));
create table yeast (alcohol_tolerance numeric(2, 0), fermentation_temp_max numeric(3, 1), fermentation_temp_min numeric(3, 1), flocculation int4, fermentation_type int4, yeast_type varchar(255), id int8 not null, producer_id int8, primary key (id));
alter table beer_style add constraint UK_sowx1f440q3tqgxq5wc67l59e unique (beer_style_name);
alter table country add constraint UK_qrkn270121aljmucrdbnmd35p unique (country_name);
alter table additive add constraint FKs71wv6q8broma753ungc4s8i foreign key (id) references ingredient;
alter table batch add constraint FKseg5h3yqh1uyfl46vut0o8fay foreign key (batch_comments_id) references batch_comments;
alter table batch add constraint FKkhjvygi25r299vx1dx7pjqvcy foreign key (beer_style_id) references beer_style;
alter table batch_comments add constraint FKs4tce7mavhst58nkvmwb7euek foreign key (batch_id) references batch;
alter table batch_ingredient add constraint FKlfko1nq7bp1tue31uijr8kdkw foreign key (batch_id) references batch;
alter table batch_ingredient add constraint FKfwsoy5y5sgvxecegg9a7n4xmj foreign key (ingredient_id) references ingredient;
alter table batch_mash_temperature add constraint FK7w59yuwy97q2d960hnbmc49ny foreign key (batch_id) references batch;
alter table batch_mash_temperature add constraint FKbojm3lss3qhq6wftqfc0k5cka foreign key (mash_temperature_id) references mash_temperature;
alter table hop add constraint FKq9k4gqqviv7qiiu2kfe0x7cc foreign key (country_id) references country;
alter table hop add constraint FKnw8lbijgra4k1vvmutqcdqhbs foreign key (id) references ingredient;
alter table malt add constraint FKoic4jn99yvdjep9wlxy0fc6jg foreign key (country_id) references country;
alter table malt add constraint FKp4nne04jqsxhkmrmamvaof9ca foreign key (producer_id) references producer;
alter table malt add constraint FKp07pikubnyw581g9axvp3dld4 foreign key (id) references ingredient;
alter table yeast add constraint FK64ef7w304mr2wmahw1jypqfnh foreign key (producer_id) references producer;
alter table yeast add constraint FK2tixgnwt8iaj2j8bk6epkgb9f foreign key (id) references ingredient;
create table additive (id int8 not null, primary key (id));
create table batch (id  bigserial not null, rager_ibu numeric(19, 2), tinseth_ibu numeric(19, 2), alcohol_volume numeric(19, 2), amount_of_priming_material int4 not null, batch_number int4, blg1 numeric(19, 2), blg2 numeric(19, 2), boiling_time int4, bottling_date date, calculated_ibu numeric(19, 2), creation_date date, designation varchar(255), efficiency numeric(19, 2), fermentation_date date, lautering_type varchar(255), lautering_water_amount int4 check (lautering_water_amount<=20), mashing_water_amount int4 check (mashing_water_amount<=20), maturation_date date, priming_material varchar(255), volume numeric(4, 1), batch_comments_id int8, beer_style_id int8, primary key (id));
create table batch_comments (id  bigserial not null, comment text, batch_id int8, primary key (id));
create table batch_ingredient (amount int4 not null, batch_id int8 not null, ingredient_id int8 not null, way_of_serving varchar(255) not null, primary key (amount, batch_id, ingredient_id, way_of_serving));
create table batch_mash_temperature (batch_id int8 not null, mash_temperature_id int8 not null, minutes int4 not null, sequence int4 not null, primary key (batch_id, mash_temperature_id, minutes, sequence));
create table beer_style (id  bigserial not null, abv1 numeric(4, 1), abv2 numeric(4, 1), beer_style_name varchar(255), ebc1 int4 check (ebc1>=1), ebc2 int4 check (ebc2>=1), final_blg_1 numeric(4, 1), final_blg_2 numeric(4, 1), final_gravity_1 numeric(4, 3), final_gravity_2 numeric(4, 3), ibu1 int4 check (ibu1>=1), ibu2 int4 check (ibu2>=1), original_blg_1 numeric(4, 1), original_blg_2 numeric(4, 1), original_gravity_1 numeric(4, 3), original_gravity_2 numeric(4, 3), srm1 int4, srm2 int4, primary key (id));
create table country (id  bigserial not null, country_code varchar(255), country_name varchar(255), primary key (id));
create table hop (alpha_acid_max numeric(3, 1), alpha_acid_min numeric(3, 1), aroma_hop boolean, bitter_hop boolean, id int8 not null, country_id int8, primary key (id));
create table ingredient (type varchar(31) not null, id  bigserial not null, name varchar(255), primary key (id));
create table malt (malt_ebc int4, malt_filling int4, malt_usage varchar(255), id int8 not null, country_id int8, producer_id int8 not null, primary key (id));
create table mash_temperature (id  bigserial not null, description varchar(255), rest_name varchar(255), temp1 int4, temp2 int4, primary key (id));
create table producer (id  bigserial not null, producer_name varchar(255), product varchar(255), primary key (id));
create table yeast (alcohol_tolerance numeric(2, 0), fermentation_temp_max numeric(3, 1), fermentation_temp_min numeric(3, 1), flocculation int4, fermentation_type int4, yeast_type varchar(255), id int8 not null, producer_id int8, primary key (id));
alter table beer_style add constraint UK_sowx1f440q3tqgxq5wc67l59e unique (beer_style_name);
alter table country add constraint UK_qrkn270121aljmucrdbnmd35p unique (country_name);
alter table additive add constraint FKs71wv6q8broma753ungc4s8i foreign key (id) references ingredient;
alter table batch add constraint FKseg5h3yqh1uyfl46vut0o8fay foreign key (batch_comments_id) references batch_comments;
alter table batch add constraint FKkhjvygi25r299vx1dx7pjqvcy foreign key (beer_style_id) references beer_style;
alter table batch_comments add constraint FKs4tce7mavhst58nkvmwb7euek foreign key (batch_id) references batch;
alter table batch_ingredient add constraint FKlfko1nq7bp1tue31uijr8kdkw foreign key (batch_id) references batch;
alter table batch_ingredient add constraint FKfwsoy5y5sgvxecegg9a7n4xmj foreign key (ingredient_id) references ingredient;
alter table batch_mash_temperature add constraint FK7w59yuwy97q2d960hnbmc49ny foreign key (batch_id) references batch;
alter table batch_mash_temperature add constraint FKbojm3lss3qhq6wftqfc0k5cka foreign key (mash_temperature_id) references mash_temperature;
alter table hop add constraint FKq9k4gqqviv7qiiu2kfe0x7cc foreign key (country_id) references country;
alter table hop add constraint FKnw8lbijgra4k1vvmutqcdqhbs foreign key (id) references ingredient;
alter table malt add constraint FKoic4jn99yvdjep9wlxy0fc6jg foreign key (country_id) references country;
alter table malt add constraint FKp4nne04jqsxhkmrmamvaof9ca foreign key (producer_id) references producer;
alter table malt add constraint FKp07pikubnyw581g9axvp3dld4 foreign key (id) references ingredient;
alter table yeast add constraint FK64ef7w304mr2wmahw1jypqfnh foreign key (producer_id) references producer;
alter table yeast add constraint FK2tixgnwt8iaj2j8bk6epkgb9f foreign key (id) references ingredient;
