spring:
  datasource:
    url: jdbc:mysql://localhost:3306/maruszka_dev?useTimezone=true&serverTimezone=UTC&characterEncoding=utf8
    username: maruszka_prod_user
    password: maruszka
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false