spring:
  datasource:
    url: jdbc:mysql://localhost:3306/maruszka_dev?serverTimezone=Europe/Warsaw&useJDBCCompliantTimezoneShift=true
    username: maruszka_dev_user
    password: maruszka
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false
    properties:
      hibernate:
        hbm2ddl:
          delimiter: ";"
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: maruszka_database_create.sql